import = [
  "~/.config/alacritty/themes/themes/tokyo-night-storm.toml"
]
[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true

[font]
normal.family = "CaskaydiaCove Nerd Font"
normal.style = "SemiLight"

bold.family = "CaskaydiaCove Nerd Font"
bold.style = "Regular"

italic.family = "CaskaydiaCove Nerd Font"
italic.style = "SemiLight Italic"

bold_italic.family = "CaskaydiaCove Nerd Font"
bold_italic.style = "Italic"

size = 17
